### ISSUE TITLE
which pytorch version  should be installed?

### ISSUE THREAD

**Issue by djk111** [blcuicall/NLPCC_2018_TASK2_GEC#2]
![image](https://user-images.githubusercontent.com/26111076/50335018-fce08b80-0544-11e9-8598-9b3c29cb2b84.png)
我去官网查看安装fiarseq要求pytorch版本是>=0.4.0,但你们给出的是安装0.2.0，应该安装那个版本？
希望您能解答下，谢谢！

**Comment by yangzonglin1994** [comment]
其实直接装最新版的PyTorch+fairseq也可以，然后把`run.sh`脚本里的`generate.py`替换成`interactive.py`，再移除掉一些`interactive.py`不支持的flag就可以了。
